POST http://localhost:8080/kategoria
Content-Type: application/json

{
  "Nazwa": "Sprzęt",
  "IdKategoria": "1"
}

###

POST http://localhost:8080/produkt
Content-Type: application/json

{
  "Nazwa": "Sztanga",
  "Cena": "27.17",
  "IdKategoria": "1",
  "Dostepnosc": "true"
}

###

POST http://localhost:8080/produkt
Content-Type: application/json

{
  "Nazwa": "Hantel",
  "Cena": "7.99",
  "IdKategoria": "1",
  "Dostepnosc": "true"
}

###

POST http://localhost:8080/produkt
Content-Type: application/json

{
  "Nazwa": "Guma Oporowa",
  "Kod": "cc",
  "Cena": "9.99",
  "IdKategoria": "1",
  "Dostepnosc": "false"
}

###

POST http://localhost:8080/produkt
Content-Type: application/json

{
  "Nazwa": "Obciążenie",
  "Cena": "5.49",
  "IdKategoria": "1",
  "Dostepnosc": "false"
}
###
POST http://localhost:8080/kategoria
Content-Type: application/json

{
  "Nazwa": "Suplementy",
  "IdKategoria": "2"
}
###
POST http://localhost:8080/produkt
Content-Type: application/json

{
  "Nazwa": "Kreatyna",
  "Cena": "5.49",
  "IdKategoria": "2",
  "Dostepnosc" : "true"
}
###
POST http://localhost:8080/produkt
Content-Type: application/json

{
  "Nazwa": "Białko",
  "Cena": "6.89",
  "IdKategoria": "2",
  "Dostepnosc" : "true"
}
###

POST http://localhost:8080/produkt
Content-Type: application/json

{
  "Nazwa": "Witaminy",
  "Cena": "2.89",
  "IdKategoria": "2",
  "Dostepnosc" : "false"
}
###

POST http://localhost:8080/produkt
Content-Type: application/json

{
  "Nazwa": "Spalacz tłuszczu",
  "Cena": "7.20",
  "IdKategoria": "2",
  "Dostepnosc" : "true"
}
###

POST http://localhost:8080/produkt
Content-Type: application/json

{
  "Nazwa": "Gryf",
  "Cena": "32",
  "IdKategoria": "1",
  "Dostepnosc": "true"
}

###

POST http://localhost:8080/produkt
Content-Type: application/json

{
  "Nazwa": "Drążek",
  "Cena": "15.80",
  "IdKategoria": "1",
  "Dostepnosc": "true"
}

###

POST http://localhost:8080/kategoria
Content-Type: application/json

{
  "Nazwa": "Usługi",
  "IdKategoria": "3"
}

###

POST http://localhost:8080/produkt
Content-Type: application/json

{
  "Nazwa": "Plan dietetyczny",
  "Cena": "45",
  "IdKategoria": "3",
  "Dostepnosc": "true"
}

###

GET http://localhost:8080/produkt
Content-Type: application/json

###

GET http://localhost:8080/kategoria
Content-Type: application/json



